### ISSUE TITLE
无法跳转到抖音扫码

### ISSUE THREAD

**Issue by xiegongping** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#1]
![image](https://user-images.githubusercontent.com/4705284/145360930-ebfe9eaa-456c-42c3-b2a7-7627fa8f37cb.png)
获取授权临时票据，返回结果是不是不对，这个不是跳转到抖音扫码的页码吗，现在没法跳转。

**Comment by fudiwei** [comment]
忽略这个接口，不应该有它，后面会删掉。

你应该按文档里给的规则拼接 URL、将这个 URL 生成一个二维码让用户用抖音扫一扫，并不是发送请求到这个 URL 上。
