### ISSUE TITLE
添加泛知识库角色系统接口

### ISSUE THREAD

**Issue by a878851497** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#13]
> **⚠⚠ 请注意：不符合格式要求的 Issue 可能会被直接关闭。**

---

**关于建议的简单描述**

新增泛知识库角色系统接口

---

**实现思路或解决方案**

抖音开放平台已经推出了泛知识库角色系统，目前还没有沙盒功能
按照平台的说法，角色系统会取代之前的资质系统，所以最好可以在sdk中添加相关接口

---

**补充说明**

https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/open-capacity/Industry/pan-knowledge/knowledge-role

**Comment by a878851497** [comment]
我来做这个

**Comment by fudiwei** [comment]
Release v2.5.0.
