### ISSUE TITLE
[FEATURE] 添加交易系统相关接口

### ISSUE THREAD

**Issue by a878851497** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#15]
---

**关于建议的简单描述**

添加交易系统相关接口
知识库、本地生活的交易不使用担保交易，而是使用独立的交易系统

---

**实现思路或解决方案**
参考文档：
在业务的交易能力上，抖音提供了担保支付系统和交易系统，两个系统对于接入的小程序行业有规范要求。对于生活服务，泛知识和外卖行业需要交易系统的能力接口，其他行业可以使用[担保支付系统](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/open-capacity/guaranteed-payment/introduction)的能力接口，详细信息请见 [小程序交易能力接入规范](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/operation/management/specification/trade)

https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/open-capacity/trade-system/introduction

---

**补充说明**

**Comment by code-jar** [comment]
这个已经开始了吗？ 需要用到 如果有开分支我可以参与

**Comment by fudiwei** [comment]
> 这个已经开始了吗？ 需要用到 如果有开分支我可以参与

@code-jar 欢迎贡献代码 😀

**Comment by fudiwei** [comment]
现已支持。
