### ISSUE TITLE
TikTokResponse类中的ErrorCode 及 ErrorDescription 为NULL

### ISSUE THREAD

**Issue by xiegongping** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#2]
![image](https://user-images.githubusercontent.com/4705284/145371936-621c2f84-eec4-4a00-9b0e-adeb767361e7.png)
没有赋值，应该一直都是NULL。
那么 IsSuccessful() 方法的逻辑要改，ErrorCode.GetValueOrDefault() == 0 应该要去掉。虽然不会影响结果，但是不合理。

**Comment by fudiwei** [comment]
这是 JSON 反序列化回来的字段，本就不需要手动赋值，跟上面那几个 `RawProperty` 不一样。

**Comment by xiegongping** [comment]
![image](https://user-images.githubusercontent.com/4705284/145500103-89cd0f5e-1992-4008-a505-ec4785302511.png)
抖音返回的结果 这两个字段在Data里面，并不会在最外层的结构体中呢。

**Comment by fudiwei** [comment]
大部分是在 `extra` 里面，也有部分接口是会在外层的，比如这种 https://open.douyin.com/platform/doc/6848806532054812686
