### ISSUE TITLE
缺少参数 count

### ISSUE THREAD

**Issue by xiegongping** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#3]
![image](https://user-images.githubusercontent.com/4705284/145500375-922a4ea8-f12b-4e4a-8fe3-882df14e1a68.png)
![image](https://user-images.githubusercontent.com/4705284/145500409-ff087824-45b2-4f35-adda-8a3226f11053.png)

**Comment by fudiwei** [comment]
Fix this on [release v1.0.0-rc.2](https://www.nuget.org/packages/SKIT.FlurlHttpClient.ByteDance.TikTok/1.0.0-rc.2).
