### ISSUE TITLE
抖音小游戏  目前发现有2个方法自动生成的签名不对

### ISSUE THREAD

**Issue by kbtkbt-wy** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#33]
文档中要求 请求的参数都参与签名 ，sdk中少了bill_no和扣除(赠送)数量字段参与签名 
ExecuteAppsGameWalletGamePayAsync和ExecuteAppsGameWalletGamePayAsync
![image](https://github.com/fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance/assets/65989803/4884040f-f74f-4f9d-99c4-76bf4446d994)

**Comment by fudiwei** [comment]
已修复，感谢反馈。

将随下一版本 Release，敬请留意。
