### ISSUE TITLE
IsSuccessful()判断逻辑不正确

### ISSUE THREAD

**Issue by xiegongping** [fudiwei/DotNetCore.SKIT.FlurlHttpClient.ByteDance#4]
![image](https://user-images.githubusercontent.com/4705284/145761135-dedb4c72-e5b4-4cce-9182-d293a4dfc0b0.png)
能拿到数据，但是返回的结果IsSuccessful()==false

**Comment by fudiwei** [comment]
此时 `Extra?.ErrorCode.GetValueOrDefault()` 结果是什么？

**Comment by xiegongping** [comment]
![image](https://user-images.githubusercontent.com/4705284/145920596-3c93f20a-d9ef-4b2f-8dc1-203713730bb0.png)
结果为NULL

**Comment by fudiwei** [comment]
奇怪了……`int?` 的 `GetValueOrDefault()` 不应该返回的是  `default(int)`、即 `0` 么……😂 你现在是在什么环境下运行的？

**Comment by fudiwei** [comment]
我知道问题了，`Extra` 为 `null` 时，`?.` Null 条件运算符会直接返回 `null`。

**Comment by xiegongping** [comment]
return RawStatus == 200 &&
                ErrorCode.GetValueOrDefault() == 0 &&
                (Extra?.ErrorCode).GetValueOrDefault() == 0 &&
                (Extra?.SubErrorCode).GetValueOrDefault() == 0;

加个括号就可以了

**Comment by fudiwei** [comment]
@xiegongping 来个 PR？

**Comment by xiegongping** [comment]
OK .晚点，刚下班。
